# Each platform contributes the sources that talk to its own window system and the system libraries those sources need.
if(APPLE)
    set(WORKPANE_PLATFORM_SOURCES
        platform/macos/ApplicationMenu.mm
        platform/macos/ExitDescriptor.cpp
        platform/macos/InputMethod.mm
        platform/macos/MacFonts.h
        platform/macos/MacFonts.mm
        platform/macos/MacNativeViewHost.h
        platform/macos/MacNativeViewHost.mm
        platform/macos/MacRegistryEntry.h
        platform/macos/MacRegistryEntry.mm
        platform/macos/MacSysctl.h
        platform/macos/MacSysctl.mm
        platform/macos/MacText.h
        platform/macos/MacText.mm
        platform/macos/MacWebView.h
        platform/macos/MacWebView.mm
        platform/macos/NativeSystemInspector.mm
        platform/macos/NativeSystemServices.mm
        platform/macos/NativeViews.mm
        platform/macos/NativeWindowStyle.mm
        platform/macos/ProcessDirectory.cpp
        platform/macos/ScrollWheel.cpp
        platform/posix/ExitDescriptor.h
        platform/posix/FileAccess.cpp
        platform/posix/FileReplacement.cpp
        platform/posix/NativeProcesses.cpp
        platform/posix/NativePseudoTerminals.cpp
        platform/posix/NetworkInterfaceList.cpp
        platform/posix/NetworkInterfaceList.h
        platform/posix/ParentConsole.cpp
        platform/posix/PathText.cpp
        platform/posix/PosixPipe.cpp
        platform/posix/PosixPipe.h
        platform/posix/PosixProcess.cpp
        platform/posix/PosixProcess.h
        platform/posix/PosixPseudoTerminal.cpp
        platform/posix/PosixPseudoTerminal.h
        platform/posix/ProcessSignals.cpp
        platform/posix/ProgramImage.cpp
        platform/posix/ProgramImage.h
        platform/posix/ShellHistory.cpp
        platform/posix/ShellHistory.h
        platform/posix/WebViewEngine.cpp
        platform/posix/WebViewEngine.h
    )
    set(WORKPANE_PLATFORM_LIBRARIES "-framework Cocoa" "-framework CoreText" "-framework IOKit" "-framework QuartzCore" "-framework WebKit" webview::core)
elseif(WIN32)
    set(WORKPANE_PLATFORM_SOURCES
        platform/TimeZoneDatabase.cpp
        platform/TimeZoneDatabase.h
        platform/windows/ApplicationMenu.cpp
        platform/windows/FileAccess.cpp
        platform/windows/FileReplacement.cpp
        platform/windows/InputMethod.cpp
        platform/windows/NativeProcesses.cpp
        platform/windows/NativePseudoTerminals.cpp
        platform/windows/NativeSystemInspector.cpp
        platform/windows/NativeSystemServices.cpp
        platform/windows/NativeViews.cpp
        platform/windows/NativeWindowStyle.cpp
        platform/windows/ParentConsole.cpp
        platform/windows/PathText.cpp
        platform/windows/ProcessSignals.cpp
        platform/windows/ScrollWheel.cpp
        platform/windows/SmbiosTable.cpp
        platform/windows/SmbiosTable.h
        platform/windows/WindowsNativeViewHost.cpp
        platform/windows/WindowsNativeViewHost.h
        platform/windows/WindowsEnvironment.cpp
        platform/windows/WindowsEnvironment.h
        platform/windows/WindowsFonts.cpp
        platform/windows/WindowsFonts.h
        platform/windows/WindowsProcess.cpp
        platform/windows/WindowsProcess.h
        platform/windows/WindowsRegistry.cpp
        platform/windows/WindowsRegistry.h
        platform/windows/WindowsPseudoTerminal.cpp
        platform/windows/WindowsPseudoTerminal.h
        platform/windows/WindowsText.cpp
        platform/windows/WindowsText.h
        platform/windows/WindowsWebEnvironment.cpp
        platform/windows/WindowsWebEnvironment.h
        platform/windows/WindowsWebView.cpp
        platform/windows/WindowsWebView.h
    )
    set(WORKPANE_PLATFORM_LIBRARIES workpane_webview2 advapi32 comdlg32 dwmapi dwrite dxgi imm32 iphlpapi ntdll ole32 setupapi shell32 user32 ws2_32)
else()
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(WORKPANE_GTK REQUIRED IMPORTED_TARGET gtk+-3.0 gtk+-x11-3.0 fontconfig)
    find_package(X11 REQUIRED)
    set(WORKPANE_PLATFORM_SOURCES
        platform/TimeZoneDatabase.cpp
        platform/TimeZoneDatabase.h
        platform/linux/ApplicationMenu.cpp
        platform/linux/InputMethod.cpp
        platform/linux/LinuxEventWatcher.cpp
        platform/linux/LinuxEventWatcher.h
        platform/linux/LinuxNativeViewHost.cpp
        platform/linux/LinuxNativeViewHost.h
        platform/linux/LinuxProcess.cpp
        platform/linux/LinuxProcess.h
        platform/linux/ExitDescriptor.cpp
        platform/linux/LinuxSysfs.cpp
        platform/linux/LinuxSysfs.h
        platform/linux/LinuxWebView.cpp
        platform/linux/LinuxWebView.h
        platform/linux/NativeSystemInspector.cpp
        platform/linux/NativeSystemServices.cpp
        platform/linux/NativeViews.cpp
        platform/linux/NativeWindowStyle.cpp
        platform/linux/ProcessDirectory.cpp
        platform/linux/ScrollWheel.cpp
        platform/posix/ExitDescriptor.h
        platform/posix/FileAccess.cpp
        platform/posix/FileReplacement.cpp
        platform/posix/NativeProcesses.cpp
        platform/posix/NativePseudoTerminals.cpp
        platform/posix/NetworkInterfaceList.cpp
        platform/posix/NetworkInterfaceList.h
        platform/posix/ParentConsole.cpp
        platform/posix/PathText.cpp
        platform/posix/PosixPipe.cpp
        platform/posix/PosixPipe.h
        platform/posix/PosixProcess.cpp
        platform/posix/PosixProcess.h
        platform/posix/PosixPseudoTerminal.cpp
        platform/posix/PosixPseudoTerminal.h
        platform/posix/ProcessSignals.cpp
        platform/posix/ProgramImage.cpp
        platform/posix/ProgramImage.h
        platform/posix/ShellHistory.cpp
        platform/posix/ShellHistory.h
        platform/posix/WebViewEngine.cpp
        platform/posix/WebViewEngine.h
    )
    set(WORKPANE_PLATFORM_LIBRARIES PkgConfig::WORKPANE_GTK X11::X11 X11::Xext util webview::core)
endif()
